name = "gltangle"
version = "0.1.0"
description = "Tangle Markdown code blocks to a code file"
licences = ["EUPL-1.2"]
repository = { type = "github", user = "RisGar", repo = "gltangle" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glint = ">= 1.2.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.5.1 and < 2.0.0"
